=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/schema/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://com.disc_au.soap.aggregator"
	xmlns="http://com.disc_au.soap.aggregator"
	elementFormDefault="qualified">

	<xs:element name="aggregator">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="merge-root" type="xs:string"/>
				<xs:element name="merge-xsl" type="xs:string" minOccurs="0"/>
				<xs:element name="config-dir" type="xs:string" />
				<xs:element name="error-dir" type="xs:string"/>
				<xs:element name="debug-dir" type="xs:string" minOccurs="0"/>
				<xs:element name="validation-file" type="xs:string" minOccurs="0"/>
				<xs:element ref="service" maxOccurs="unbounded" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="soap-url" type="xs:string" />
				<xs:element name="soap-user" type="xs:string" minOccurs="0" />
				<xs:element name="soap-password" type="xs:string" minOccurs="0" />
				<xs:element name="soap-action" type="xs:string" minOccurs="0" />
				<xs:element name="ssl-no-host-verify" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Y"/>
							<xs:enumeration value="N"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="outbound-xsl" type="xs:string" />
				<!-- Used for masking sensitive data befor writing to the logs -->
				<xs:element name="maskRequestIn-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="maskRequestOut-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="outbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="timeoutMillis" type="xs:integer" />
				<xs:element name="extract-element" type="xs:string" minOccurs="0"/>
				<xs:element name="content-type" type="xs:string" minOccurs="0"/><!-- Specify the Content-Type http header that SOAP Aggregator will send. Default to text/xml -->
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="save-location" type="xs:string" minOccurs="0" />
				<xs:element name="host" type="xs:string" minOccurs="0" />
				<xs:element name="username" type="xs:string" minOccurs="0" />
				<xs:element name="password" type="xs:string" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/health_application/cua/config_NXS.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/debug</debug-dir>

	<service name="CUA" type="soap">
		<soap-url>https://testservices.cua.com.au/Service.svc</soap-url>
		<soap-action>http://HSL.OMS.Public.API.Service/IService/SubmitMembershipTransaction</soap-action>
		<outbound-xsl>cua/outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>keyname=Choosi,keycode=CTM27ctm</outbound-xsl-parms>
		<inbound-xsl>cua/inbound.xsl</inbound-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRequestOut-xsl>maskRequestOutHSL.xsl</maskRequestOut-xsl>
		<timeoutMillis>120000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/roadside/config_NXI.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/roadside</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/roadside/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/roadside/debug</debug-dir>

	<service name="AGIS" type="url-encoded">
		<soap-url>http://192.168.149.65/ctm/rating/roadside_price_service_AGIS.jsp</soap-url>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AGIS,quoteRoot=http://nxi.secure.comparethemarket.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="1FOW" type="url-encoded">
		<soap-url>http://192.168.149.65/ctm/rating/roadside_price_service_1FOW.jsp</soap-url>
		<outbound-xsl>1FOW_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000004,sourceId=TEST000004</outbound-xsl-parms>
		<inbound-xsl>1FOW_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=1FOW,quoteRoot=https://nxi.ecommerce.disconline.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="24-7" type="url-encoded">
		<soap-url>http://192.168.149.65/ctm/rating/roadside_price_service_24-7.jsp</soap-url>
		<outbound-xsl>24-7_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>24-7_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=24-7</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="365R" type="url-encoded">
		<soap-url>http://192.168.149.65/ctm/rating/roadside_price_service_365R.jsp</soap-url>
		<outbound-xsl>365R_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>365R_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=365R</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGAR" type="url-encoded">
		<soap-url>http://192.168.149.65/ctm/rating/roadside_price_service_AGAR.jsp</soap-url>
		<outbound-xsl>AGAR_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>AGAR_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AGAR</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/health_application/auf/config_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/debug</debug-dir>

	<service name="AUF" type="soap">
		<soap-url>https://b2b.australianunity.com.au/comparethemarket/SalesServices.asmx</soap-url>
		<soap-action>http://ws.australianunity.com.au/B2B/Broker/ProcessApplication</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>auf/outbound.xsl</outbound-xsl>
		<inbound-xsl>auf/inbound.xsl</inbound-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRequestOut-xsl>auf/maskRequestOut.xsl</maskRequestOut-xsl>
		<timeoutMillis>120000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/utilities/config_results_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/utilities</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/utilities/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/utilities/debug</debug-dir>
	<validation-file>WEB-INF/xsd/utilities/utilitiesQuoteResults.xsd</validation-file>

	<service name="RESULTS" type="SOAP">
		<soap-url>https://websvc.switchwise.com.au:444/switchwiseCTM_1_5_13/SwitchwiseSearchService.svc/Products/</soap-url>
		<soap-user>ctm</soap-user>
		<soap-password>Ctm#138s</soap-password>
		<outbound-xsl>utilities_products_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms></outbound-xsl-parms>
		<inbound-xsl>utilities_products_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=DEFAULT</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/utilities/config_allretailers_NXQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-allretailers.xsl</merge-xsl>
	<config-dir>aggregator/utilities</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/utilities/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/utilities/debug</debug-dir>

	<service name="ALLRETAILERS" type="SOAP">
		<soap-url>http://websvcpreprod.switchwise.com.au/switchwise1_5_10/SwitchwiseSearchService.svc/AllRetailers</soap-url>
		<soap-method>GET</soap-method>
		<outbound-xsl>utilities_allretailers_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms></outbound-xsl-parms>
		<inbound-xsl>utilities_allretailers_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=DEFAULT</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/travel/config_DUIN.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"			
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">
		
	<merge-root>soap-response</merge-root>	
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>/WEB-INF/aggregator/travel</config-dir>
	<error-dir>c:/dev/web_cc/WebContent/WEB-INF/aggregator/travel/errors</error-dir>
	<debug-dir>c:/dev/web_cc/WebContent/WEB-INF/aggregator/travel/debug</debug-dir>
			
	<service name="DUIN" type="url-encoded">
		<soap-url>http://localhost:8080/cc/rating/travel_price_service_DUIN.jsp</soap-url>
		<outbound-xsl>DUIN_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>DUIN_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=DUIN</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>	
</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/roadside/config_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/roadside</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/roadside/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/roadside/debug</debug-dir>
	<validation-file>WEB-INF/xsd/roadside/roadsidePriceResult.xsd</validation-file>

	<service name="AGIS" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/rating/roadside_price_result.jsp?providerId=54</soap-url>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AGIS,quoteRoot=https://ecommerce.disconline.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="1FOW" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/rating/roadside_price_result.jsp?providerId=44</soap-url>
		<outbound-xsl>1FOW_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000004,sourceId=TEST000004</outbound-xsl-parms>
		<inbound-xsl>1FOW_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=1FOW,quoteRoot=https://ecommerce.disconline.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="24-7" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/rating/roadside_price_result.jsp?providerId=289</soap-url>
		<outbound-xsl>24-7_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>24-7_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=24-7</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="365R" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/rating/roadside_price_result.jsp?providerId=302</soap-url>
		<outbound-xsl>365R_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>365R_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=365R</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/life/config_product_apply_QA.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"			
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">
		
	<merge-root>soap-response</merge-root>	
	<merge-xsl>merge-product-selection.xsl</merge-xsl>
	<config-dir>/WEB-INF/aggregator/life</config-dir>
	<error-dir>/WEB-INF/aggregator/life/errors</error-dir>
	<debug-dir>/WEB-INF/aggregator/life/debug</debug-dir>
		
	<service name="APPLY" type="SOAP">
		<soap-url>https://enterpriseapi.lifebroker.com.au/2-3-0/quote/select</soap-url>
		<soap-user>UATcompthemkt</soap-user>
		<soap-password>lI9hW2qIlx2f4G</soap-password>
		<outbound-xsl>life_product_apply_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms></outbound-xsl-parms>
		<inbound-xsl>life_product_apply_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=APPLY</inbound-xsl-parms>
		<timeoutMillis>60000</timeoutMillis>
	</service>	
		
</aggregator>
