=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/schema/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://com.disc_au.soap.aggregator"
	xmlns="http://com.disc_au.soap.aggregator"
	elementFormDefault="qualified">

	<xs:element name="aggregator">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="merge-root" type="xs:string"/>
				<xs:element name="merge-xsl" type="xs:string" minOccurs="0"/>
				<xs:element name="config-dir" type="xs:string" />
				<xs:element name="error-dir" type="xs:string"/>
				<xs:element name="debug-dir" type="xs:string" minOccurs="0"/>
				<xs:element name="validation-file" type="xs:string" minOccurs="0"/>
				<xs:element ref="service" maxOccurs="unbounded" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="soap-url" type="xs:string" />
				<xs:element name="soap-user" type="xs:string" minOccurs="0" />
				<xs:element name="soap-password" type="xs:string" minOccurs="0" />
				<xs:element name="soap-action" type="xs:string" minOccurs="0" />
				<xs:element name="ssl-no-host-verify" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Y"/>
							<xs:enumeration value="N"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="outbound-xsl" type="xs:string" />
				<!-- Used for masking sensitive data befor writing to the logs -->
				<xs:element name="maskRequestIn-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="maskRequestOut-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="outbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="timeoutMillis" type="xs:integer" />
				<xs:element name="extract-element" type="xs:string" minOccurs="0"/>
				<xs:element name="content-type" type="xs:string" minOccurs="0"/><!-- Specify the Content-Type http header that SOAP Aggregator will send. Default to text/xml -->
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="save-location" type="xs:string" minOccurs="0" />
				<xs:element name="host" type="xs:string" minOccurs="0" />
				<xs:element name="username" type="xs:string" minOccurs="0" />
				<xs:element name="password" type="xs:string" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/home/config_results_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/home</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/home/app-logs-errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/home/app-logs-debug</debug-dir>
	<validation-file>WEB-INF/xsd/home/homeQuoteResults.xsd</validation-file>

	<service name="AGIS_BUDD" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/gethomeQuotes</soap-url>
		<soap-action>gethomeQuotes</soap-action>
		<outbound-xsl>AGIS/outbound_results.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000100,sourceId=0000000001,schemaVersion=3.0</outbound-xsl-parms>
		<inbound-xsl>AGIS/inbound_results.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=BUDD-05-29,service=AGIS_BUDD,certServer=secure.</inbound-xsl-parms>
		<timeoutMillis>40000</timeoutMillis>
	</service>

	<service name="AGIS_VIRG" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/gethomeQuotes</soap-url>
		<soap-action>gethomeQuotes</soap-action>
		<outbound-xsl>AGIS/outbound_results.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000100,sourceId=0000000002,schemaVersion=3.0</outbound-xsl-parms>
		<inbound-xsl>AGIS/inbound_results.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=VIRG-05-26,service=AGIS_VIRG,certServer=secure.</inbound-xsl-parms>
		<timeoutMillis>40000</timeoutMillis>
	</service>

	<service name="AGIS_EXDD" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/gethomeQuotes</soap-url>
		<soap-action>gethomeQuotes</soap-action>
		<outbound-xsl>AGIS/outbound_results.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000100,sourceId=0000000003,schemaVersion=3.0</outbound-xsl-parms>
		<inbound-xsl>AGIS/inbound_results.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=EXDD-05-21,service=AGIS_EXDD,certServer=secure.</inbound-xsl-parms>
		<timeoutMillis>40000</timeoutMillis>
	</service>

<!-- 	<service name="AGIS_OZIC" type="soap"> -->
<!-- 		<soap-url>https://ecommerce.disconline.com.au/services/3.0/gethomeQuotes</soap-url> -->
<!-- 		<soap-action>gethomeQuotes</soap-action> -->
<!-- 		<outbound-xsl>AGIS/outbound_results.xsl</outbound-xsl> -->
<!-- 		<outbound-xsl-parms>partnerId=CTM0000100,sourceId=0000000004,schemaVersion=3.0</outbound-xsl-parms> -->
<!-- 		<inbound-xsl>AGIS/inbound_results.xsl</inbound-xsl> -->
<!-- 		<inbound-xsl-parms>defaultProductId=OZIC-05-26,service=AGIS_OZIC,certServer=secure.</inbound-xsl-parms> -->
<!-- 		<timeoutMillis>40000</timeoutMillis> -->
<!-- 	</service> -->

	<service name="REIN" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/ctm/rating/home/home_price_service.jsp?service=REIN</soap-url>
		<outbound-xsl>Hollard/copy_nodes_outbound.xsl</outbound-xsl>
		<inbound-xsl>Hollard/copy_nodes_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=REIN-02-01</inbound-xsl-parms>
		<timeoutMillis>25000</timeoutMillis>
	</service>

	<service name="WOOL" type="url-encoded">
		<soap-url>https://ecommerce.disconline.com.au/ctm/rating/home/home_price_service.jsp?service=WOOL</soap-url>
		<outbound-xsl>Hollard/copy_nodes_outbound.xsl</outbound-xsl>
		<inbound-xsl>Hollard/copy_nodes_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=WOOL-02-01</inbound-xsl-parms>
		<timeoutMillis>25000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/ip/config_request_call_QA.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"			
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">
		
	<merge-root>soap-response</merge-root>	
	<merge-xsl>merge-request-call.xsl</merge-xsl>
	<config-dir>/WEB-INF/aggregator/ip</config-dir>
	<error-dir>/WEB-INF/aggregator/ip/errors</error-dir>
	<debug-dir>/WEB-INF/aggregator/ip/debug</debug-dir>
		
	<service name="REQUESTCALL" type="SOAP">
		<soap-url>https://enterpriseapi.lifebroker.com.au/2-3-0/lead/new</soap-url>
		<soap-user>UATcompthemkt</soap-user>
		<soap-password>lI9hW2qIlx2f4G</soap-password>
		<outbound-xsl>ip_request_call_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms></outbound-xsl-parms>
		<inbound-xsl>ip_request_call_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=DEFAULT</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>	
		
</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/get_prices/config_NXS.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/get_prices</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/debug</debug-dir>

	<service name="AGIS_BUDD" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=BUDD-05-01,service=AGIS_BUDD,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
<!--
	<service name="AGIS_IECO" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000002</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=IECO-05-09,service=AGIS_IECO,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
-->
	<service name="AGIS_1FOW" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000003</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=1FOW-05-02,service=AGIS_1FOW,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_VIRG" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000004</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=VIRG-05-11,service=AGIS_VIRG,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_RETI" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000005</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=RETI-05-03,service=AGIS_RETI,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
<!--
	<service name="AGIS_CBCK" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000006</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=CBCK-05-08,service=AGIS_CBCK,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
-->
	<service name="AGIS_OZIC" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000007</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=OZIC-05-01,service=AGIS_OZIC,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_EXPO" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/3.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000003,sourceId=0000000008</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=EXPO-05-16,service=AGIS_EXPO,certServer=qa.secure.</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="REIN" type="url-encoded">
		<soap-url>http://192.168.149.233/ctm/rating/car/car_price_service_REIN.jsp</soap-url>
		<outbound-xsl>REIN_copy_nodes.xsl</outbound-xsl>
		<inbound-xsl>REIN_copy_nodes.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=REIN-01-02,urlRoot=http://uat.realinsurance.interesting.com.au/referrer/</inbound-xsl-parms>
		<timeoutMillis>25000</timeoutMillis>
	</service>

	<service name="AI" type="soap">
		<soap-url>http://203.35.12.182/SSGatewayTest/SSGateway.asmx</soap-url>
		<soap-action>http://www.softsure.co.za/GetMultiPremium</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>AI_outbound.xsl</outbound-xsl>
		<inbound-xsl>AI_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=AI-01-01,quoteURL=http://testweb.aiinsurance.com.au/Buy/buy/KnockOutQuestions/</inbound-xsl-parms>
		<timeoutMillis>40000</timeoutMillis>
	</service>

	<service name="WOOL" type="url-encoded">
		<soap-url>http://192.168.149.233/ctm/rating/car/car_price_service_WOOL.jsp</soap-url>
		<outbound-xsl>WOOL_copy_nodes.xsl</outbound-xsl>
		<inbound-xsl>WOOL_copy_nodes.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=WOOL-01-02</inbound-xsl-parms>
		<timeoutMillis>25000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/health_application/hcf/config_NXI.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/health_application/debug</debug-dir>

	<service name="HCF" type="soap">
		<soap-url>https://www.uat.hcf.com.au/EAPP/EAPPService.svc/EnrolNewMember</soap-url>
		<soap-action>https://www.uat.hcf.com.au/EAPP/EAPPService.svc/EnrolNewMember</soap-action>
		<outbound-xsl>hcf/outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>keycode=P@$$w0rd</outbound-xsl-parms>
		<inbound-xsl>hcf/inbound.xsl</inbound-xsl>
		<maskRequestOut-xsl>hcf/maskRequestOut.xsl</maskRequestOut-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRespIn-xsl>hcf/maskRespIn.xsl</maskRespIn-xsl>
		<timeoutMillis>240000</timeoutMillis>
		<extract-element>GetHCFSaleInfo</extract-element>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/health_application/auf/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<debug-dir>health_application/app-logs-debug</debug-dir>
	<validation-file>WEB-INF/xsd/health/AUF/healthApplication.xsd</validation-file>

	<service name="AUF" type="soap">
		<soap-url>http://localhost:8080/ctm/broken.jsp</soap-url>
		<soap-action>http://ws.australianunity.com.au/B2B/Broker/ProcessApplication</soap-action>
		<outbound-xsl>auf/outbound.xsl</outbound-xsl>
		<inbound-xsl>auf/inbound.xsl</inbound-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRequestOut-xsl>auf/maskRequestOut.xsl</maskRequestOut-xsl>
		<timeoutMillis>240000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/life/config_results_life.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/life</config-dir>
	<error-dir>aggregator/life/app-logs-errors</error-dir>
	<debug-dir>life/app-logs-debug</debug-dir>
	<validation-file>WEB-INF/xsd/life/lifeQuoteResults.xsd</validation-file>

<!-- 
	<service name="BUDD_RESULTS" type="SOAP">
		<soap-url>https://nxq.ecommerce.disconline.com.au/services/3.1/getLifeQuotes</soap-url>
		<soap-action>https://nxq.ecommerce.disconline.com.au/services/3.1/getLifeQuote</soap-action>
		<outbound-xsl>life_results_AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>sourceId=0000000001</outbound-xsl-parms>
		<inbound-xsl>life_results_AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>company=budget_direct,companyCode=BUDD</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
-->

	<service name="OZIC_RESULTS" type="SOAP">
		<soap-url>https://nxq.ecommerce.disconline.com.au/services/3.1/getLifeQuotes</soap-url>
		<soap-action>https://nxq.ecommerce.disconline.com.au/services/3.1/getLifeQuotes</soap-action>
		<outbound-xsl>life_results_AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>sourceId=0000000002</outbound-xsl-parms>
		<inbound-xsl>life_results_AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>company=ozicare,companyCode=OZIC</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="LB_RESULTS" type="SOAP">
		<soap-url>https://enterpriseapi.lifebroker.com.au/2-7-0/term-quote/new</soap-url>
		<soap-user>UATcompthemkt</soap-user>
		<soap-password>lI9hW2qIlx2f4G</soap-password>
		<outbound-xsl>life_results_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>vertical=life</outbound-xsl-parms>
		<inbound-xsl>life_results_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=DEFAULT</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/health_application/thf/config_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<debug-dir>health_application/debug</debug-dir>
	<validation-file>WEB-INF/xsd/health/THF/healthApplication.xsd</validation-file>

	<service name="THF" type="soap">
		<soap-url>https://online.teachershealth.com.au/Service.svc</soap-url>
		<soap-action>http://HSL.OMS.Public.API.Service/IService/SubmitMembershipSTP</soap-action>
		<outbound-xsl>thf/outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>keyname=HFAPctm,keycode=wNxEdqyX</outbound-xsl-parms>
		<inbound-xsl>thf/inbound.xsl</inbound-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRequestOut-xsl>maskRequestOutHSL.xsl</maskRequestOut-xsl>
		<timeoutMillis>240000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/roadside/config_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/roadside</config-dir>
	<debug-dir>roadside/debug</debug-dir>
	<validation-file>WEB-INF/xsd/roadside/roadsidePriceResult.xsd</validation-file>

	<service name="AGIS" type="url-encoded">
		<soap-url>http://127.0.0.1:8080/ctm/rating/roadside_price_result.jsp?providerId=54</soap-url>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AGIS,quoteRoot=https://secure.budgetdirect.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="1FOW" type="url-encoded">
		<soap-url>http://127.0.0.1:8080/ctm/rating/roadside_price_result.jsp?providerId=44</soap-url>
		<outbound-xsl>1FOW_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000004,sourceId=TEST000004</outbound-xsl-parms>
		<inbound-xsl>1FOW_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=1FOW,quoteRoot=https://1stforwomen.disconline.com.au</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="24-7" type="url-encoded">
		<soap-url>http://127.0.0.1:8080/ctm/rating/roadside_price_result.jsp?providerId=289</soap-url>
		<outbound-xsl>24-7_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>24-7_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=24-7</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<!--<service name="365R" type="url-encoded">
		<soap-url>http://127.0.0.1:8080/ctm/rating/roadside_price_result.jsp?providerId=302</soap-url>
		<outbound-xsl>365R_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>365R_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=365R</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>-->

	<service name="M247" type="url-encoded">
		<soap-url>http://127.0.0.1:8080/ctm/rating/roadside_price_result.jsp?providerId=313</soap-url>
		<outbound-xsl>M247_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000010,sourceId=TEST000010</outbound-xsl-parms>
		<inbound-xsl>M247_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=M247</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>
