=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/schema/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://com.disc_au.soap.aggregator"
	xmlns="http://com.disc_au.soap.aggregator"
	elementFormDefault="qualified">

	<xs:element name="aggregator">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="merge-root" type="xs:string"/>
				<xs:element name="merge-xsl" type="xs:string" minOccurs="0"/>
				<xs:element name="config-dir" type="xs:string" />
				<xs:element name="error-dir" type="xs:string"/>
				<xs:element name="debug-dir" type="xs:string" minOccurs="0"/>
				<xs:element name="validation-file" type="xs:string" minOccurs="0"/>
				<xs:element ref="service" maxOccurs="unbounded" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="soap-url" type="xs:string" />
				<xs:element name="soap-user" type="xs:string" minOccurs="0" />
				<xs:element name="soap-password" type="xs:string" minOccurs="0" />
				<xs:element name="soap-action" type="xs:string" minOccurs="0" />
				<xs:element name="ssl-no-host-verify" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Y"/>
							<xs:enumeration value="N"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="outbound-xsl" type="xs:string" />
				<!-- Used for masking sensitive data befor writing to the logs -->
				<xs:element name="maskRequestIn-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="maskRequestOut-xsl" type="xs:string" minOccurs="0"  />
				<xs:element name="outbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl" type="xs:string" minOccurs="0" />
				<xs:element name="inbound-xsl-parms" type="xs:string" minOccurs="0" />
				<xs:element name="timeoutMillis" type="xs:integer" />
				<xs:element name="extract-element" type="xs:string" minOccurs="0"/>
				<xs:element name="content-type" type="xs:string" minOccurs="0"/><!-- Specify the Content-Type http header that SOAP Aggregator will send. Default to text/xml -->
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="save-location" type="xs:string" minOccurs="0" />
				<xs:element name="host" type="xs:string" minOccurs="0" />
				<xs:element name="username" type="xs:string" minOccurs="0" />
				<xs:element name="password" type="xs:string" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/get_prices/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>../aggregator/get_prices</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/debug</debug-dir>

	<service name="AGIS_BUDD" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=BUDD-05-01,service=AGIS_BUDD</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_IECO" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000002</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=IECO-05-09,service=AGIS_IECO</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_1FOW" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000003</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=1FOW-05-02,service=AGIS_1FOW</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_VIRG" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000004</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=VIRG-05-11,service=AGIS_VIRG</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_RETI" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000005</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=RETI-05-03,service=AGIS_RETI</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_CBCK" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000006</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=CBCK-05-08,service=AGIS_CBCK</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_OZIC" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000007</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=OZIC-05-01,service=AGIS_OZIC</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AGIS_EXPO" type="soap">
		<soap-url>https://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000008</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=EXPO-05-13,service=AGIS_EXPO</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
<!--
	<service name="REAL_PAYD" type="url-encoded">
		<soap-url>http://uat.realservices.interesting.com.au/Services/Quote</soap-url>
		<outbound-xsl>REAL_outbound.xsl</outbound-xsl>
		<inbound-xsl>REAL_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=PAYD-01-01,urlRoot=http://uat.realinsurance.interesting.com.au/referrer/</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
-->
	<service name="AI" type="soap">
		<soap-url>http://119.225.81.101/SSGatewayTest/SSGateway.asmx</soap-url>
		<soap-action>http://www.softsure.co.za/GetSpecifiedVehiclePremium</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>AI_outbound.xsl</outbound-xsl>
		<inbound-xsl>AI_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AI-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="CRSR" type="soap">
		<soap-url>https://staging.avea.com.au:2001/QuotationService.svc</soap-url>
		<soap-action>http://services.fastr.com.au/Quotation/IQuotationService/RequestInitialQuotation</soap-action>
		<outbound-xsl>AVEA_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>servicePassword=captaincompare</outbound-xsl-parms>
		<inbound-xsl>CRSR_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=CRSR-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AUBN" type="soap">
		<soap-url>https://staging.avea.com.au:2001/QuotationService.svc</soap-url>
		<soap-action>http://services.fastr.com.au/Quotation/IQuotationService/RequestInitialQuotation</soap-action>
		<outbound-xsl>AVEA_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>servicePassword=captaincompareauto</outbound-xsl-parms>
		<inbound-xsl>AUBN_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AUBN-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/travel/config_AMEX_QA.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"			
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">
		
	<merge-root>soap-response</merge-root>	
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>/aggregator/travel</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/travel/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/travel/debug</debug-dir>
		
<service name="AMEX" type="url-encoded">
		<soap-url>http://qa.ecommerce.disconline.com.au/cc/rating/travel_price_service_AMEX.jsp</soap-url>
		<outbound-xsl>AMEX_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AMEX_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AMEX</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>	
	<service name="AMEX" type="url-encoded">
		<soap-url>http://qa.ecommerce.disconline.com.au/cc/rating/travel_price_service_AMEX_multi.jsp</soap-url>
		<outbound-xsl>AMEX_outbound_multi.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AMEX_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=NODEFAULT,service=AMEX</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>	

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/get_prices/config_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="https://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="https://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>/aggregator/get_prices</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/errors</error-dir>
	<debug-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/get_prices/debug</debug-dir>

	<service name="AGIS_BUDD" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000002,sourceId=0000000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=BUDD-05-01,service=AGIS_BUDD</inbound-xsl-parms>
		<timeoutMillis>30000</timeoutMillis>
	</service>

	<service name="AGIS_OTH1" type="soap">
		<soap-url>https://ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000002,sourceId=0000000002</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=OZIC-05-01,service=AGIS_OZIC</inbound-xsl-parms>
		<timeoutMillis>30000</timeoutMillis>
	</service>

	<service name="REAL_PAYD" type="url-encoded">
		<soap-url>https://quote.realinsurance.com.au/ReferralServices/Services/Quote</soap-url>
		<outbound-xsl>REAL_outbound.xsl</outbound-xsl>
		<inbound-xsl>REAL_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=PAYD-01-01,urlRoot=https://www.realinsurance.com.au/Referrer/</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
<!--
	<service name="AI" type="soap">
		<soap-url>https://119.225.81.101/SSGateway/SSGateway.asmx</soap-url>
		<soap-action>http://www.softsure.co.za/GetSpecifiedVehiclePremium</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>AI_outbound.xsl</outbound-xsl>
		<inbound-xsl>AI_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AI-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>
-->
	<service name="AI" type="soap">
		<soap-url>https://119.225.81.101/SSGateway/SSGateway.asmx</soap-url>
		<soap-action>http://www.softsure.co.za/GetVehiclePremium</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>AI_outbound.xsl</outbound-xsl>
		<inbound-xsl>AI_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AI-01-01</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="CRSR" type="soap">
		<soap-url>https://services.avea.com.au:8080/QuotationService.svc</soap-url>
		<soap-action>http://services.fastr.com.au/Quotation/IQuotationService/RequestInitialQuotation</soap-action>
		<outbound-xsl>AVEA_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>servicePassword=captaincompare</outbound-xsl-parms>
		<inbound-xsl>CRSR_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=CRSR-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AUBN" type="soap">
		<soap-url>https://services.avea.com.au:8080/QuotationService.svc</soap-url>
		<soap-action>http://services.fastr.com.au/Quotation/IQuotationService/RequestInitialQuotation</soap-action>
		<outbound-xsl>AVEA_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>servicePassword=captaincompareauto</outbound-xsl-parms>
		<inbound-xsl>AUBN_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AUBN-01-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/home/config_WOOL_quote_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<config-dir>aggregator/home</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/home/errors</error-dir>
	<debug-dir>home/debug-rein</debug-dir>

	<service name="WOOLQUOTE" type="soap">
		<soap-url>https://everyone.realinsurance.com.au/v2/AggregatorService.svc</soap-url>
		<soap-action>http://tempuri.org/IAggregatorService/GetHomeQuote</soap-action>
		<outbound-xsl>Hollard/outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CTM0000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>Hollard/inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=WOOL-02-01,service=WOOL</inbound-xsl-parms>
		<timeoutMillis>35000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/health_application/auf/config_NXQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
            xmlns="http://com.disc_au.soap.aggregator">

    <merge-root>soap-response</merge-root>
    <merge-xsl>merge-results.xsl</merge-xsl>
    <config-dir>aggregator/health_application</config-dir>
    <debug-dir>health_application/debug</debug-dir>
    <validation-file>WEB-INF/xsd/health/AUF/healthApplication.xsd</validation-file>
    <service name="AUF" type="soap">
        <soap-url>https://stage-sales.b2b.health-insurance.australianunity.com.au/CompareTheMarket.Soap11</soap-url>
        <soap-action>http://ws.australianunity.com.au/B2B/Broker/ProcessApplication</soap-action>
        <ssl-no-host-verify>Y</ssl-no-host-verify>
        <outbound-xsl>auf/outbound.xsl</outbound-xsl>
        <inbound-xsl>auf/inbound.xsl</inbound-xsl>
        <maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
        <maskRequestOut-xsl>auf/maskRequestOut.xsl</maskRequestOut-xsl>
        <timeoutMillis>240000</timeoutMillis>
    </service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/home/config_WOOL_init_PRO.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<config-dir>aggregator/home</config-dir>
	<error-dir>/usr/aih/app-logs/ctm/WEB-INF/aggregator/home/errors</error-dir>
	<debug-dir>home/debug-rein</debug-dir>

	<service name="WOOLINIT" type="soap">
		<soap-url>https://everyone.realinsurance.com.au/v2/AggregatorService.svc</soap-url>
		<soap-action>http://tempuri.org/IAggregatorService/Initialize</soap-action>
		<outbound-xsl>Hollard/init_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>keyname=ctmprod01,keypass=%^56tgBy,siteKey=WoolworthsHomeBaseCTM</outbound-xsl-parms>
		<inbound-xsl>Hollard/init_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=WOOL-02-01</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/src/main/webapp/WEB-INF/aggregator/health_application/qch/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<nabGateway>
		<gatewayURL>https://testservices.qchfund.com.au/NAB/QCH_CTM_IFrame.aspx</gatewayURL>
		<domain>https://testservices.qchfund.com.au</domain>
	</nabGateway>

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/health_application</config-dir>
	<error-dir>aggregator/health_application/app-logs-errors</error-dir>
	<debug-dir>health_application/app-logs-debug</debug-dir>
	<validation-file>WEB-INF/xsd/health/QCH/healthApplication.xsd</validation-file>

	<service name="QCH" type="soap">
		<soap-url>https://testservices.qchfund.com.au/Service.svc</soap-url>
		<soap-action>http://HSL.OMS.Public.API.Service/IService/SubmitMembershipSTP</soap-action>
		<outbound-xsl>qch/outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>keyname=CTM,keycode=compare2015</outbound-xsl-parms>
		<inbound-xsl>qch/inbound.xsl</inbound-xsl>
		<maskRequestIn-xsl>maskRequestIn.xsl</maskRequestIn-xsl>
		<maskRequestOut-xsl>maskRequestOutHSL.xsl</maskRequestOut-xsl>
		<timeoutMillis>240000</timeoutMillis>
		<content-type>application/soap+xml; charset=utf-8</content-type>
	</service>

</aggregator>

=== andreygolubevctm/andreygolubevctm/WebContent/WEB-INF/aggregator/get_prices/webloadtest_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<aggregator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://com.disc_au.soap.aggregator ../schema/config.xsd"
			xmlns="http://com.disc_au.soap.aggregator">

	<merge-root>soap-response</merge-root>
	<merge-xsl>merge-results.xsl</merge-xsl>
	<config-dir>aggregator/get_prices</config-dir>
	<error-dir>aggregator/get_prices/app-logs-errors</error-dir>
	<debug-dir>aggregator/get_prices/app-logs-debug</debug-dir>

	<service name="AGIS_BUDD" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000001</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=BUDD-05-01</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_IECO" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000002</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=IECO-05-09</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_1FOW" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000003</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=1FOW-05-02</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_VIRG" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000004</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=VIRG-05-11</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_RETI" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000005</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=RETI-05-03</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_CBCK" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000006</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=CBCK-05-08</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_OZIC" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000007</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>defaultProductId=OZIC-05-01</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>

	<service name="AGIS_EXPO" type="soap">
		<soap-url>http://qa.ecommerce.disconline.com.au/services/2.0/getCarQuotes</soap-url>
		<soap-action>getCarQuotes</soap-action>
		<outbound-xsl>AGIS_outbound.xsl</outbound-xsl>
		<outbound-xsl-parms>partnerId=CC00000001,sourceId=TEST000008</outbound-xsl-parms>
		<inbound-xsl>AGIS_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=EXPO-05-13</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>
<!--
	<service name="REAL_PAYD" type="url-encoded">
		<soap-url>http://uat.realservices.interesting.com.au/Services/Quote</soap-url>
		<outbound-xsl>REAL_outbound.xsl</outbound-xsl>
		<inbound-xsl>REAL_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=PAYD-01-01,urlRoot=https://uat.realinsurance.interesting.com.au/referrer/</inbound-xsl-parms>
		<timeoutMillis>20000</timeoutMillis>
	</service>

	<service name="AI" type="soap">
		<soap-url>https://119.225.81.101/SSGatewayTest/SSGateway.asmx</soap-url>
		<soap-action>http://www.softsure.co.za/GetSpecifiedVehiclePremium</soap-action>
		<ssl-no-host-verify>Y</ssl-no-host-verify>
		<outbound-xsl>AI_outbound.xsl</outbound-xsl>
		<inbound-xsl>AI_inbound.xsl</inbound-xsl>
		<inbound-xsl-parms>productId=AI-01-01</inbound-xsl-parms>
		<timeoutMillis>10000</timeoutMillis>
	</service>
-->
</aggregator>
